# Generated by Django 3.1.6 on 2021-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='notas',
            field=models.TextField(null=True),
        ),
    ]
